export const data = [
  { title: "3D animator", tags: [], description: {} },
  { title: "3D Generalist", tags: [], description: {} },
  { title: "Video Editor", tags: [], description: {} },
  { title: "Motion Designer ", tags: [], description: {} },
  { title: "Content creation", tags: [], description: {} },
  { title: "Backend", tags: [], description: {} },
  { title: "Project Manager", tags: [], description: {} },
  { title: "Project Manager Backend ", tags: [], description: {} },
  { title: "Маркетолог", tags: [], description: {} },
  { title: "QA", tags: [], description: {} },
  { title: "Jira", tags: [], description: {} },
  { title: "IOS", tags: [], description: {} },
  { title: "Unity", tags: [], description: {} },
  { title: "TL IOS", tags: [], description: {} },
  { title: "TL Unity", tags: [], description: {} },
  { title: "Script&Director", tags: [], description: {} },
  { title: "Recruiter", tags: [], description: {} },
  { title: "ML Developer", tags: [], description: {} },
  { title: "System Administrator", tags: [], description: {} },
  { title: "Graphic designer", tags: [], description: {} },
  { title: "Lawyer", tags: [], description: {} },
  { title: "3D artist  ", tags: [], description: {} },
  { title: "Ui/Ux дизайнер ", tags: [], description: {} },
];
