import icon from "../../../public/Icon.png";

export const data = [
  { image: icon, title: "Widget Pixel Pets", description: "Pixel Pals is an incredible app for customizing your Home Screen and Lock Screen, as well as Live Activities, allowing you to place adorable pets called Pixel Pals that you can customize and enjoy as you swipe through your apps or unlock your phone, making each interaction just that much happier!", video: "https://www.youtube.com/embed/IRp7k3wj4OY?si=dXd0gW4XQ4NjrfZd" },
  { image: icon, title: "Widget Pixel Pets", description: "Pixel Pals is an incredible app for customizing your Home Screen and Lock Screen, as well as Live Activities, allowing you to place adorable pets called Pixel Pals that you can customize and enjoy as you swipe through your apps or unlock your phone, making each interaction just that much happier!", video: "https://www.youtube.com/embed/IRp7k3wj4OY?si=dXd0gW4XQ4NjrfZd" },
  { image: icon, title: "Widget Pixel Pets", description: "Pixel Pals is an incredible app for customizing your Home Screen and Lock Screen, as well as Live Activities, allowing you to place adorable pets called Pixel Pals that you can customize and enjoy as you swipe through your apps or unlock your phone, making each interaction just that much happier!", video: "https://www.youtube.com/embed/IRp7k3wj4OY?si=dXd0gW4XQ4NjrfZd" },
  { image: icon, title: "Widget Pixel Pets", description: "Pixel Pals is an incredible app for customizing your Home Screen and Lock Screen, as well as Live Activities, allowing you to place adorable pets called Pixel Pals that you can customize and enjoy as you swipe through your apps or unlock your phone, making each interaction just that much happier!", video: "https://www.youtube.com/embed/IRp7k3wj4OY?si=dXd0gW4XQ4NjrfZd" },
  { image: icon, title: "Widget Pixel Pets", description: "Pixel Pals is an incredible app for customizing your Home Screen and Lock Screen, as well as Live Activities, allowing you to place adorable pets called Pixel Pals that you can customize and enjoy as you swipe through your apps or unlock your phone, making each interaction just that much happier!", video: "https://www.youtube.com/embed/IRp7k3wj4OY?si=dXd0gW4XQ4NjrfZd" },
  { image: icon, title: "Widget Pixel Pets", description: "Pixel Pals is an incredible app for customizing your Home Screen and Lock Screen, as well as Live Activities, allowing you to place adorable pets called Pixel Pals that you can customize and enjoy as you swipe through your apps or unlock your phone, making each interaction just that much happier!", video: "https://www.youtube.com/embed/IRp7k3wj4OY?si=dXd0gW4XQ4NjrfZd" },
  { image: icon, title: "Widget Pixel Pets", description: "Pixel Pals is an incredible app for customizing your Home Screen and Lock Screen, as well as Live Activities, allowing you to place adorable pets called Pixel Pals that you can customize and enjoy as you swipe through your apps or unlock your phone, making each interaction just that much happier!", video: "https://www.youtube.com/embed/IRp7k3wj4OY?si=dXd0gW4XQ4NjrfZd" },
  { image: icon, title: "Widget Pixel Pets", description: "Pixel Pals is an incredible app for customizing your Home Screen and Lock Screen, as well as Live Activities, allowing you to place adorable pets called Pixel Pals that you can customize and enjoy as you swipe through your apps or unlock your phone, making each interaction just that much happier!", video: "https://www.youtube.com/embed/IRp7k3wj4OY?si=dXd0gW4XQ4NjrfZd" },
  { image: icon, title: "Widget Pixel Pets", description: "Pixel Pals is an incredible app for customizing your Home Screen and Lock Screen, as well as Live Activities, allowing you to place adorable pets called Pixel Pals that you can customize and enjoy as you swipe through your apps or unlock your phone, making each interaction just that much happier!", video: "https://www.youtube.com/embed/IRp7k3wj4OY?si=dXd0gW4XQ4NjrfZd" },
  { image: icon, title: "Widget Pixel Pets", description: "Pixel Pals is an incredible app for customizing your Home Screen and Lock Screen, as well as Live Activities, allowing you to place adorable pets called Pixel Pals that you can customize and enjoy as you swipe through your apps or unlock your phone, making each interaction just that much happier!", video: "https://www.youtube.com/embed/IRp7k3wj4OY?si=dXd0gW4XQ4NjrfZd" },
  { image: icon, title: "Widget Pixel Pets", description: "Pixel Pals is an incredible app for customizing your Home Screen and Lock Screen, as well as Live Activities, allowing you to place adorable pets called Pixel Pals that you can customize and enjoy as you swipe through your apps or unlock your phone, making each interaction just that much happier!", video: "https://www.youtube.com/embed/IRp7k3wj4OY?si=dXd0gW4XQ4NjrfZd" },
  { image: icon, title: "Widget Pixel Pets", description: "Pixel Pals is an incredible app for customizing your Home Screen and Lock Screen, as well as Live Activities, allowing you to place adorable pets called Pixel Pals that you can customize and enjoy as you swipe through your apps or unlock your phone, making each interaction just that much happier!", video: "https://www.youtube.com/embed/IRp7k3wj4OY?si=dXd0gW4XQ4NjrfZd" },
  { image: icon, title: "Widget Pixel Pets", description: "Pixel Pals is an incredible app for customizing your Home Screen and Lock Screen, as well as Live Activities, allowing you to place adorable pets called Pixel Pals that you can customize and enjoy as you swipe through your apps or unlock your phone, making each interaction just that much happier!", video: "https://www.youtube.com/embed/IRp7k3wj4OY?si=dXd0gW4XQ4NjrfZd" },
  { image: icon, title: "Widget Pixel Pets", description: "Pixel Pals is an incredible app for customizing your Home Screen and Lock Screen, as well as Live Activities, allowing you to place adorable pets called Pixel Pals that you can customize and enjoy as you swipe through your apps or unlock your phone, making each interaction just that much happier!", video: "https://www.youtube.com/embed/IRp7k3wj4OY?si=dXd0gW4XQ4NjrfZd" },
  { image: icon, title: "Widget Pixel Pets", description: "Pixel Pals is an incredible app for customizing your Home Screen and Lock Screen, as well as Live Activities, allowing you to place adorable pets called Pixel Pals that you can customize and enjoy as you swipe through your apps or unlock your phone, making each interaction just that much happier!", video: "https://www.youtube.com/embed/IRp7k3wj4OY?si=dXd0gW4XQ4NjrfZd" },
  { image: icon, title: "Widget Pixel Pets", description: "Pixel Pals is an incredible app for customizing your Home Screen and Lock Screen, as well as Live Activities, allowing you to place adorable pets called Pixel Pals that you can customize and enjoy as you swipe through your apps or unlock your phone, making each interaction just that much happier!", video: "https://www.youtube.com/embed/IRp7k3wj4OY?si=dXd0gW4XQ4NjrfZd" },
  { image: icon, title: "Widget Pixel Pets", description: "Pixel Pals is an incredible app for customizing your Home Screen and Lock Screen, as well as Live Activities, allowing you to place adorable pets called Pixel Pals that you can customize and enjoy as you swipe through your apps or unlock your phone, making each interaction just that much happier!", video: "https://www.youtube.com/embed/IRp7k3wj4OY?si=dXd0gW4XQ4NjrfZd" },
  { image: icon, title: "Widget Pixel Pets", description: "Pixel Pals is an incredible app for customizing your Home Screen and Lock Screen, as well as Live Activities, allowing you to place adorable pets called Pixel Pals that you can customize and enjoy as you swipe through your apps or unlock your phone, making each interaction just that much happier!", video: "https://www.youtube.com/embed/IRp7k3wj4OY?si=dXd0gW4XQ4NjrfZd" },
  { image: icon, title: "Widget Pixel Pets", description: "Pixel Pals is an incredible app for customizing your Home Screen and Lock Screen, as well as Live Activities, allowing you to place adorable pets called Pixel Pals that you can customize and enjoy as you swipe through your apps or unlock your phone, making each interaction just that much happier!", video: "https://www.youtube.com/embed/IRp7k3wj4OY?si=dXd0gW4XQ4NjrfZd" },
  { image: icon, title: "Widget Pixel Pets", description: "Pixel Pals is an incredible app for customizing your Home Screen and Lock Screen, as well as Live Activities, allowing you to place adorable pets called Pixel Pals that you can customize and enjoy as you swipe through your apps or unlock your phone, making each interaction just that much happier!", video: "https://www.youtube.com/embed/IRp7k3wj4OY?si=dXd0gW4XQ4NjrfZd" },
];
